module.exports = {
  STATE: {
    PENDING: "PENDING",
    SUCCEEDED: "SUCCEEDED",
    FAILED: "FAILED",
    CANCELED: "CANCELED",
    EXPIRED: "EXPIRED",
  },
  PAYMETHOD: {
    PAYME: "PAYME",
    ATMCARD: "ATMCARD",
    MANUAL_BANK: "MANUAL_BANK",
    VN_PAY: "VN_PAY",
    CREDIT: "CREDIT",
    MOMO: "MOMO",
    ZALO_PAY: "ZALO_PAY",
  },
};
